{% set name = "libgdal-ecwjp2" %}
{% set version = "2.4.0" %}
{% set maj_min_constraint = "2.4.*" %}
{% set maj_min_ver = "2.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: gdal-{{ version }}-{{ name }}.tar.xz
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.xz
  sha256: c3791dcc6d37e59f6efa86e2df2a55a4485237b0a48e330ae08949f0cdf00f27
  patches:
    # Use multiple cores on Windows
    - patches/0001-multiprocessor.patch  # [win]
    # Minimal drivers build
    - patches/0002-minimal-drivers.patch  # [win]
    # Fix macro redefinition error
    - patches/0003-cvs-redefinition.patch  # [win]
    # Fix builds without curl
    # In master and 2.4 branch: https://github.com/OSGeo/gdal/issues/1251
    - patches/0004-missing-ogrngw.patch

build:
  number: 1000
  # For now...
  skip: True  # [not win]

requirements:
  build:
    - m2-patch  # [win]
    - pkg-config >=0.21  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ecwjp2-sdk
    # External libs needed for minimal drivers build
    - geos
    - geotiff
    - jpeg
    - libiconv
    - libpng
    - libtiff
    - libuuid  # [linux]
    - proj4
  run:
    - libgdal {{ maj_min_constraint }}
    - ecwjp2-sdk


test:
  # files:
  #   TODO: add small file, to test with ogrinfo
  #   - test_data
  commands:
    - if not exist %LIBRARY_LIB%\\gdalplugins\\{{ maj_min_ver }}\\gdal_ECW_JP2ECW.dll exit 1  # [win]

about:
  home: http://www.gdal.org
  license: MIT
  license_file: LICENSE.TXT
  summary: ERDAS ECW and JPEG2000 plugin for GDAL/OGR
  description: |
    GDAL is a translator library for raster and vector geospatial data formats
    that is released under an X/MIT style Open Source license by the Open
    Source Geospatial Foundation.
  doc_url: https://www.gdal.org/frmt_ecw.html
  dev_url: https://github.com/OSGeo/gdal/tree/master/gdal/frmts/ecw

extra:
  recipe-maintainers:
    - dakcarto
